name: IAST
on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: SonarCloud Scan
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Required for SonarCloud)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarCloud scanner
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar-scanner-cli
          restore-keys: sonar-scanner-cli

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=aut2025
            -Dsonar.projectKey=aut2025
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
